# Generated by Django 3.2.9 on 2022-02-01 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': '学部',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(max_length=150)),
                ('lecture_number', models.IntegerField()),
                ('lecture_teacher', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '講義名',
                'db_table': 'lectures',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.department')),
            ],
            options={
                'verbose_name_plural': '学科',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesiton', models.FileField(upload_to='questions/')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.lectures')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.AddField(
            model_name='lectures',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subjects'),
        ),
    ]
