# Generated by Django 3.2.9 on 2022-02-01 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='quesiton',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='questions',
            name='lecture',
            field=models.ForeignKey(limit_choices_to={'lecture_number': 311522}, on_delete=django.db.models.deletion.CASCADE, to='questions.lectures'),
        ),
    ]
