# Generated by Django 3.2.9 on 2022-02-01 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivatetokens',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 11, 4, 36, 509079)),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 11, 4, 36, 509431)),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 11, 4, 36, 509440)),
        ),
    ]
