# Generated by Django 3.2.9 on 2022-02-01 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 11, 4, 36, 510033)),
        ),
        migrations.AlterField(
            model_name='boards',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 11, 4, 36, 510042)),
        ),
    ]
