# Generated by Django 3.2.9 on 2022-02-01 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20220201_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 12, 29, 31, 348371)),
        ),
        migrations.AlterField(
            model_name='boards',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 12, 29, 31, 348381)),
        ),
    ]
